Multiplication of two matrices by using * and @ and .dot()

In [5]:
import numpy as np

#Multiplication of 2 matrices by each other of size 3x3

matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[5,2,6],[5,6,7],[7,6,4]])


In [6]:
matrix1*matrix2 # elementwise multiplication

array([[ 5,  4, 18],
       [20, 30, 42],
       [49, 48, 36]])

In [7]:
matrix1@matrix2

array([[ 36,  32,  32],
       [ 87,  74,  83],
       [138, 116, 134]])

In [8]:
matrix1.dot(matrix2)

array([[ 36,  32,  32],
       [ 87,  74,  83],
       [138, 116, 134]])