Multidimensional arrays can have one index per axis. 

These indices are given in a tuple separated by commas:

In [1]:
import numpy as np

def f(x,y):
    return 10*x+y

b=np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [2]:
b[2,3]

23

In [3]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [4]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [5]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [6]:
b[-1]

array([40, 41, 42, 43])

In [7]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [8]:
c[1,...] # same as c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [9]:
c[...,2] # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

In [11]:
for row in c:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [12]:
# if one wants to perform an operation on each element in the array... 
#        one can use the flat attribute which is an iterator over all the elements of the array

for element in c.flat:
    print(element)

0
1
2
10
12
13
100
101
102
110
112
113
