In [1]:
Q 5, 10, 16, 17, 26, 35, 

Q 0 - flat iterator

Q 21 - using np.tile() function to make checkerboard

Q 38 - generate f()

Q 41 = np.add()

Q 52 = importing scipy

Q 53 = converting float to integer

Q 55 = ndenumerate

Q 61 = argmin()

Q 69 - diag() function

Q 62 = iterator, summing 2 arrays using nditer() function

Q 65 = bincount()

SyntaxError: invalid syntax (<ipython-input-1-9202483a7d46>, line 1)

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
# Q 0.

import numpy as np

def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)


for element in b.flat:   # flat as iterator
    print(element)
  # print(element*2)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [3]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kate/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Kate/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kate/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Kate/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kate/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Kate/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kate/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Kate/anaconda\\Library\\include']


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
# ?????

%run `python -c "import numpy; numpy.info(numpy.add)"`


Exception: File `'`python.py'` not found.

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
X=np.zeros(10) # null vector of size 10

X[4]=1       # fifth value is index [4]
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
Y=np.arange(10,50)
Y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
Y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
np.random.randint(0,9,(3,3))

array([[7, 1, 1],
       [0, 2, 7],
       [6, 4, 2]])

In [14]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
A=np.array([1,2,0,0,4,0])

for i in A:
    if A[i]==0:
        pass
    else:
        print(A)

[1 2 0 0 4 0]
[1 2 0 0 4 0]
[1 2 0 0 4 0]
[1 2 0 0 4 0]
[1 2 0 0 4 0]


In [24]:
A=np.nonzero([1,2,0,0,4,0])
print(A)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [27]:
np.random((3,3,3))  # creates an error

TypeError: 'module' object is not callable

In [28]:
np.random.random((3,3,3))  #np.random.random is correct

array([[[0.03467045, 0.81409897, 0.09537364],
        [0.08682673, 0.9653573 , 0.60259142],
        [0.60324949, 0.43602218, 0.63023178]],

       [[0.82156298, 0.223501  , 0.12696972],
        [0.29178721, 0.70046462, 0.2500016 ],
        [0.97620288, 0.85230364, 0.442652  ]],

       [[0.01702372, 0.71401146, 0.41312658],
        [0.66092592, 0.95704764, 0.93188199],
        [0.41518701, 0.23329279, 0.13278491]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
S=np.random.random((10,10))
S

array([[0.2103033 , 0.66173597, 0.77084771, 0.1914918 , 0.83720716,
        0.525685  , 0.49756155, 0.31447581, 0.04870868, 0.45612549],
       [0.56082256, 0.83313064, 0.78271741, 0.62927346, 0.21493547,
        0.20999036, 0.68534732, 0.91138056, 0.21591866, 0.96740099],
       [0.87042175, 0.84055955, 0.03408535, 0.44410722, 0.8640064 ,
        0.96619201, 0.64893904, 0.97786938, 0.11587402, 0.99373691],
       [0.73346189, 0.7436967 , 0.67430268, 0.04077506, 0.88209039,
        0.64714624, 0.12704132, 0.81621573, 0.82616068, 0.91550662],
       [0.6138821 , 0.06419128, 0.68307278, 0.55377113, 0.64858086,
        0.19422468, 0.84827773, 0.78300904, 0.77577452, 0.20572351],
       [0.7102882 , 0.42197103, 0.5496415 , 0.4303798 , 0.93247934,
        0.68111013, 0.46853888, 0.58421818, 0.33829851, 0.67976919],
       [0.5878889 , 0.88269967, 0.7359378 , 0.14005874, 0.69455232,
        0.9210304 , 0.46438173, 0.19533822, 0.88743571, 0.7624405 ],
       [0.23299548, 0.32411129, 0.1550345

In [30]:
Smin, Smax=S.min(), S.max()
print(Smin, Smax)

0.03408534990249035 0.9937369090579259


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [50]:
X=np.random.random(30)  # prints 30 values between 0 and 1

Y=X.sum()/len(X)  # mean of all values in X
Y

# try to change the vector size to 1000 and see how the mean gets close to 0.5

0.45795326062647845

In [57]:
X=np.random.random(30)
X.mean()

0.43931872804782396

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [57]:
W= np.ones((10,10))  #2D array
W[1:9, 1:9]=0
W

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [62]:
W[:, [0, -1]] = 0
W[[0, -1], :] = 0
print(W)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [60]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [62]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf < np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [67]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [69]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [71]:
np.arange(336).reshape(6,7,8) 

# what does (6,7,8) shape array mean?

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [72]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [76]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))  # 8x8 matrix
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [77]:
S=np.random.random((5,5))
S=(S-np.mean(S)/np.std(S))
print(S)

[[-1.27237261 -1.03021554 -1.69881078 -1.45348995 -1.40596032]
 [-1.20027453 -1.18679746 -1.00830511 -1.09606878 -1.49377986]
 [-1.04974107 -1.38824625 -1.72177283 -1.24126219 -1.69332481]
 [-1.27664152 -0.76163499 -1.20678899 -1.35578511 -1.33247467]
 [-1.41734    -1.46731221 -1.05099064 -1.71544251 -1.21872352]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [78]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [80]:
A=np.ones((5,3))
B=np.ones((3,2))
A@B

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [84]:
C=A.dot(B)
C

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [87]:
R=np.arange(4,8)
R[::-1]   # this is reversing

array([7, 6, 5, 4])

In [88]:
# answer

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [89]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [81]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [92]:
print (np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-92-ac763a221e55>:1: RuntimeWarning: invalid value encountered in true_divide
  print (np.array(0) / np.array(0))
<ipython-input-92-ac763a221e55>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [95]:
Z1 = np.random.randint(0,10,10)
Z1

array([7, 1, 6, 8, 1, 3, 0, 4, 4, 3])

In [96]:
Z2 = np.random.randint(0,10,10)
Z2

array([5, 9, 3, 9, 0, 2, 0, 4, 3, 3])

In [97]:
print(np.intersect1d(Z1,Z2))

[0 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [82]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-82-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [100]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(today)

2021-12-07


In [101]:
print(yesterday)

2021-12-06


In [102]:
print(tomorrow)

2021-12-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [103]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [104]:
A = np.ones(3)*1
B = np.ones(3)*2

np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
C=np.multiply(A,B, out=A)
print(C)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [111]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [112]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [117]:
np.linspace(0,1,10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [118]:
np.linspace(0,1,10, endpoint=False)[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [123]:
x=np.random.random(10)
x.sort()
x

array([0.08825673, 0.10645827, 0.18728712, 0.36672079, 0.36984385,
       0.47223144, 0.54050404, 0.56694336, 0.66016986, 0.86532935])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [128]:
Z=np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [132]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
print(A==B)

[False False False False False]


In [133]:
# this is the answer

equal = np.allclose(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [3]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [11]:
x=np.random.random(10)
x[x.argmax()] = 0
x

array([0.05235842, 0.04474032, 0.6317214 , 0.14341351, 0.48194989,
       0.05024519, 0.36916289, 0.399193  , 0.        , 0.38005111])

In [12]:
x=np.arange(10)
x[x.argmax()]=0
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [14]:
X = np.arange(8)
Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [15]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)

-128
-2147483648
-9223372036854775808


In [17]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).max)

127
2147483647
9223372036854775807


In [20]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [24]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((20,20))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [34]:
Z = np.arange(100)
v = np.random.uniform(0,100)

index = (np.abs(Z-v)).argmin()
print(Z[index])

85


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [35]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-35-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [38]:
Z=np.random.random((100,2))

X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.31521469 0.11581616 0.57582485 0.30439863 0.25062431
  0.10435698 0.71270992 0.4931561  0.57042513 0.19707479 0.36169189
  0.58936144 0.02895388 0.38355219 0.63501389 0.50951499 0.39794129
  0.25367305 0.40422617 0.39317018 0.49505527 0.58063318 0.41921864
  0.50078876 0.12672501 0.43740069 0.32563816 0.57099345 0.50305365
  0.53462359 0.45928661 0.13817961 0.32748442 0.39676432 0.47696087
  0.37894905 0.22847837 0.78645049 0.38457908 0.35890859 0.72249152
  0.53804082 0.50693248 0.13755641 0.31034918 0.74716947 0.37834339
  0.2859984  0.5179386  0.49235916 0.53865641 0.60111163 0.54976645
  0.32423201 0.46407401 0.35895921 0.49958753 0.10342582 0.73157105
  0.10473254 0.4482017  0.67322574 0.54519073 0.43252721 0.5685862
  0.10105643 0.18641501 0.17904143 0.36959894 0.50020054 0.37146378
  0.63316677 0.51004651 0.23260635 0.34611983 0.3517381  0.5027794
  0.41772644 0.5685026  0.23740459 0.43928886 0.59574091 0.30548343
  0.44145365 0.28417047 0.36734346 0.21853995 0.40

In [39]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.55687173 0.72644799 0.52255245 0.32177799 0.78361627
  0.55479551 0.72958689 0.34708596 0.91105044]
 [0.55687173 0.         0.32388262 0.87071213 0.25654979 0.71374764
  0.07130765 0.99332769 0.2707836  0.71486878]
 [0.72644799 0.32388262 0.         0.83719525 0.51759789 0.47688688
  0.26007953 0.8881141  0.38004572 0.41770182]
 [0.52255245 0.87071213 0.83719525 0.         0.74295054 0.56290817
  0.82642503 0.22133442 0.60180164 0.75368721]
 [0.32177799 0.25654979 0.51759789 0.74295054 0.         0.76933341
  0.28046387 0.90997055 0.21024802 0.8315906 ]
 [0.78361627 0.71374764 0.47688688 0.56290817 0.76933341 0.
  0.64355761 0.50273895 0.55929318 0.1941255 ]
 [0.55479551 0.07130765 0.26007953 0.82642503 0.28046387 0.64355761
  0.         0.93846681 0.23758795 0.64399195]
 [0.72958689 0.99332769 0.8881141  0.22133442 0.90997055 0.50273895
  0.93846681 0.         0.73857841 0.69440268]
 [0.34708596 0.2707836  0.38004572 0.60180164 0.21024802 0.55929318
  0.23758795 0.73857

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [40]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[39 75 95 82 26 33 94 42 28 39]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [41]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-41-dc1069bf6c21>:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [42]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [43]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [47]:

X = np.random.random((5, 10))
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)


print(Y)

[[ 0.08000275  0.2252406   0.0909736  -0.21203975  0.39015623 -0.04922131
  -0.20708013  0.02603013 -0.00479311 -0.33926902]
 [ 0.24954844  0.34746087 -0.37208469 -0.2931709   0.15902669  0.39256114
  -0.45521589  0.18157163 -0.16303163 -0.04666566]
 [-0.38987278  0.32120668 -0.22807038  0.24518072 -0.52692133  0.37913513
   0.14251074 -0.49949412  0.18136419  0.37496116]
 [ 0.31308561 -0.24721003 -0.10278262  0.07705232 -0.20315558 -0.05069806
   0.20326158  0.06312781  0.16461644 -0.21729746]
 [ 0.4906645   0.02057147 -0.31958071 -0.13854595  0.5720704  -0.31273114
  -0.0163311  -0.05522607 -0.01776569 -0.22312572]]


#### 59. How to sort an array by the nth column? (★★☆)

In [51]:
Z = np.random.randint(0,10,(3,3))
print(Z)


[[1 7 2]
 [8 0 6]
 [2 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [85]:
z=np.random.randint(0,10,(3,8))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [90]:
Z = np.random.uniform(0,1,10)  # from 0 to 1, 10 values
Z

array([0.85157771, 0.94553804, 0.19436955, 0.53180024, 0.69809548,
       0.16931912, 0.80123808, 0.01966883, 0.65504657, 0.44707155])

In [91]:
z = 0.5  # given value. Which value from Z is closest to z=0.5?

m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5318002439616111


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [92]:
X=np.arange(3).reshape(1,3)
Y=np.arange(3).reshape(3,1)
it = np.nditer([X,Y,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [15]:
# answer

it = np.nditer([X,Y,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [20]:
X=np.random.randint(10,40,(1,3))
Y=np.random.randint(10,40,(3,1))

it=np.nditer([X,Y,None])
for x,y,z in it: z[...]=x+y
print(it.operands[2])

[[43 62 66]
 [28 47 51]
 [26 45 49]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [21]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 1. 1. 2. 1. 3. 7. 4. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [22]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]

F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [25]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)

sum = A.sum(axis=(-2,-1))
print(sum)

[[41 53 55 67]
 [57 71 61 67]
 [56 74 39 59]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [31]:

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.42434125 0.45289614 0.39236032 0.34144547 0.46272132 0.71948183
 0.25974546 0.56817096 0.3588539  0.38531597]


#### 69. How to get the diagonal of a dot product? (★★★)

In [94]:

A=np.array([(2,4),(3,0)])
B=np.array([(1,2),(4,5)])
y=A.dot(B)
x=np.diag(y)
x

array([18,  6])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [95]:
Z=np.array([1,2,3,4,5])
nz = 3
newZ = np.zeros(len(Z) + (len(Z)-1)*(nz))
newZ[::nz+1] = Z
print(newZ)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [51]:
X=np.arange(75).reshape(5,5,3)
Y=np.arange(25).reshape(5,5)
print(X*Y[:,:,None])

[[[   0    0    0]
  [   3    4    5]
  [  12   14   16]
  [  27   30   33]
  [  48   52   56]]

 [[  75   80   85]
  [ 108  114  120]
  [ 147  154  161]
  [ 192  200  208]
  [ 243  252  261]]

 [[ 300  310  320]
  [ 363  374  385]
  [ 432  444  456]
  [ 507  520  533]
  [ 588  602  616]]

 [[ 675  690  705]
  [ 768  784  800]
  [ 867  884  901]
  [ 972  990 1008]
  [1083 1102 1121]]

 [[1200 1220 1240]
  [1323 1344 1365]
  [1452 1474 1496]
  [1587 1610 1633]
  [1728 1752 1776]]]


#### 72. How to swap two rows of an array? (★★★)

In [101]:
# why is this not working?

a1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

a1[[0,1]] = a1[[1,0]]
print(a1)

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]]


In [67]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [73]:
triplets=np.random.randint(0,100,(10,3))

F = np.roll(triplets.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 61) ( 0, 87) ( 1, 18) ( 1, 21) ( 1, 56) ( 1, 73) ( 7, 32) ( 7, 53)
 ( 8, 25) ( 8, 98) ( 9, 20) ( 9, 50) (13, 17) (13, 27) (17, 27) (18, 73)
 (20, 50) (21, 56) (25, 98) (31, 57) (31, 90) (32, 53) (41, 59) (41, 82)
 (46, 68) (46, 99) (57, 90) (59, 82) (61, 87) (68, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [105]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)



[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [106]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=int)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [107]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [111]:
B=np.random.randint(0,2,100)
np.logical_not(B, out=B)

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [112]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.49586633, -0.08276707,  0.04588721,  0.1346354 ,  0.78474658,
       -0.19519538,  0.11992878, -0.14293725,  0.36087274,  0.10943525,
        0.22275305, -0.85221011,  0.3663176 ,  0.19364823, -0.15110279,
       -0.13333915, -0.87361649, -0.78134208, -0.05387121,  0.17873601,
        0.90930326,  0.93800702,  0.81151871,  0.62065588, -0.46658839,
       -0.43111743,  0.41678368, -0.34950992,  0.95729456,  0.099814  ,
       -0.98181283,  0.8318875 , -0.90552433,  0.06388739,  0.10490992,
        0.68356931, -0.51987327, -0.14246486,  0.70480736,  0.6074722 ,
        0.97268821,  0.53528438, -0.94240573,  0.60265435, -0.17584282,
        0.58897501, -0.75847188,  0.75606275,  0.02212132, -0.51863635,
        0.70577483,  0.7752449 ,  0.30116488,  0.07125365,  0.63019849,
       -0.10792891,  0.87356718,  0.71428488, -0.79522782,  0.86487686,
       -0.3474373 ,  0.97325055, -0.69849301,  0.55284375,  0.07125036,
        0.00479647, -0.34439275, -0.51730886,  0.91229797,  0.94

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [115]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.93141736 2.01854774 1.04997543 7.17292437 1.89322369 3.2296847
 8.62950122 8.29638586 2.24216752 9.53549871]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [116]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 8 9 5 4 5 7 0 5 1]
 [1 4 8 5 8 1 5 3 3 4]
 [0 5 2 7 2 6 5 8 6 4]
 [8 0 4 1 7 4 2 1 6 5]
 [4 3 3 1 7 5 1 2 9 1]
 [8 8 0 9 8 3 6 1 8 1]
 [6 2 3 9 0 5 9 7 3 3]
 [4 3 2 2 7 6 2 5 3 8]
 [5 3 5 1 1 3 6 5 8 2]
 [3 4 3 9 6 8 0 8 7 0]]
[[0 0 0 0 0]
 [0 3 8 9 5]
 [0 1 4 8 5]
 [0 0 5 2 7]
 [0 8 0 4 1]]


<ipython-input-116-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [120]:
from numpy.lib import stride_tricks

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
Z

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(np.arange(1,15), 4)    # if you do np.arange(15), it gives [0 1 2 3 4...14]
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [119]:
X = np.arange(1,15,dtype=np.uint32)
Y = stride_tricks.as_strided(Z,(11,4),(4,4))
print(Y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [126]:
A=np.random.randint(0,10,50)
print(np.bincount(A).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [129]:
Z = np.random.randint(0,5,(10,10))
Z

n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 4 3]
   [1 1 0]
   [0 1 1]]

  [[4 3 4]
   [1 0 2]
   [1 1 1]]

  [[3 4 2]
   [0 2 4]
   [1 1 1]]

  [[4 2 1]
   [2 4 1]
   [1 1 4]]

  [[2 1 4]
   [4 1 0]
   [1 4 2]]

  [[1 4 2]
   [1 0 4]
   [4 2 1]]

  [[4 2 4]
   [0 4 3]
   [2 1 3]]

  [[2 4 3]
   [4 3 2]
   [1 3 4]]]


 [[[1 1 0]
   [0 1 1]
   [4 0 0]]

  [[1 0 2]
   [1 1 1]
   [0 0 2]]

  [[0 2 4]
   [1 1 1]
   [0 2 2]]

  [[2 4 1]
   [1 1 4]
   [2 2 4]]

  [[4 1 0]
   [1 4 2]
   [2 4 1]]

  [[1 0 4]
   [4 2 1]
   [4 1 1]]

  [[0 4 3]
   [2 1 3]
   [1 1 3]]

  [[4 3 2]
   [1 3 4]
   [1 3 1]]]


 [[[0 1 1]
   [4 0 0]
   [3 1 3]]

  [[1 1 1]
   [0 0 2]
   [1 3 3]]

  [[1 1 1]
   [0 2 2]
   [3 3 1]]

  [[1 1 4]
   [2 2 4]
   [3 1 2]]

  [[1 4 2]
   [2 4 1]
   [1 2 0]]

  [[4 2 1]
   [4 1 1]
   [2 0 0]]

  [[2 1 3]
   [1 1 3]
   [0 0 0]]

  [[1 3 4]
   [1 3 1]
   [0 0 1]]]


 [[[4 0 0]
   [3 1 3]
   [2 3 4]]

  [[0 0 2]
   [1 3 3]
   [3 4 0]]

  [[0 2 2]
   [3 3 1]
   [4 0 1]]

  [[2 2 4]
   [3 1 2]
   [0 1 1]]

  [[2 4 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [139]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 100
print(S)

[[  9   9   4  12   9]
 [  9   3   9   8   7]
 [  4   9   6 100  15]
 [ 12   8 100   3   2]
 [  9   7  15   2   0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [141]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [142]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [153]:
G=np.arange(9000)
np.random.shuffle(G)
n=6

print(G[np.argsort(G)[-n:]])

[8994 8995 8996 8997 8998 8999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [159]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [161]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)