In [3]:

import numpy
numpy.__version__

'1.20.1'

In [4]:
import numpy as np  # this will be the way I'll be importing and using NumPy

In [5]:
np

<module 'numpy' from 'C:\\Users\\Kate\\anaconda\\lib\\site-packages\\numpy\\__init__.py'>

In [7]:
np?

In [8]:
L1=["True", "2", 3.0, 5] #heterogeneous list

In [10]:
# the built-in array module can be used to create dense arrays of a uniform type

import array
L=list(range(10))
A=array.array('i', L) # here i is a type of code indicating that contents are integers

In [11]:
# use np.array to create arrays from Python lists

np.array([1,4,2,5,3])  

array([1, 4, 2, 5, 3])

In [12]:
np.array([3.14,4,2,5,3])  #integers are upcast to floats

array([3.14, 4.  , 2.  , 5.  , 3.  ])

In [13]:
# below is one way of initializing a multidimensional array using a list of lists

np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
# create length 10 integer array filled with zeros

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# create a 3x5 floating point array filled with ones 

np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# create a 3x5 array filled with 3.14

np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
np.full((11,7), 20)

array([[20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20]])

In [21]:
# create an array filled with a linear sequence
# starts at 0, ends at 20, stepping by 2
# look how it's similar to the built-in range() function

# Be careful! The spelling is arange


np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
# create a 3x3 array of uniformly distributed random values between 0 and 1

np.random.random((3,3))

array([[6.96266055e-01, 5.96786223e-01, 5.11118909e-01],
       [5.22882421e-01, 8.50634280e-01, 3.67270066e-01],
       [4.02530329e-04, 7.98406538e-01, 8.98571294e-02]])

In [24]:
# create a 3x3 array of normally distributed random values with mean of 0 and standard deviation of 1

np.random.normal(0,1,(3,3))

array([[-0.54938862,  2.86080375, -1.00930197],
       [ 1.19095697, -0.1727815 , -0.86121341],
       [-0.79544749, -0.25560408, -0.39443888]])

In [27]:
# create a 3x3 array of random integers (randint) in the interval of [0,10). 10 exclusive

np.random.randint(0,10, (3,3))

array([[3, 6, 1],
       [5, 1, 7],
       [2, 0, 8]])

In [28]:
# create 3x3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# create uninitialized array of 3 integers
# the values will be whatever happens to already exist at that memory location

np.empty(3)

array([1., 1., 1.])