In [2]:
import numpy as np

x=np.array([20,30,40,50,60])
x

array([20, 30, 40, 50, 60])

In [4]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [5]:
z=x-y
z

array([20, 29, 38, 47, 56])

In [10]:
y**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [16]:
A=y**2+2
A

array([ 2,  3,  6, 11, 18], dtype=int32)

In [15]:
Z=x-A
Z

array([18, 27, 34, 39, 42])

----------------------------------------------------------------------------------------------------------

* and @ and dot() in matrixes

In [19]:
# np.array ( [ [],[] ] ). Be careful to have everything within []

A=np.array([[2,4], [3,0]])
B=np.array([[1,2], [4,5]])
A*B

array([[ 2,  8],
       [12,  0]])

In [20]:
# matrix product by using @

A@B

array([[18, 24],
       [ 3,  6]])

In [21]:
# dot() function returns matrix product, same as above

A.dot(B)

array([[18, 24],
       [ 3,  6]])

--------------------------------------------------------------------------------------------------------------------------



How to add 2 lists?



In [37]:
Q=np.arange(3)
Q

array([0, 1, 2])

In [38]:
R=np.array([2.0, -1.5, 4.0])
R

array([ 2. , -1.5,  4. ])

In [39]:
np.add(Q,R)

array([ 2. , -0.5,  6. ])



+= and *= in NumPy

In [27]:
rg=np.random.default_rng(1)
X=np.ones((2,3), dtype=int)
Y=rg.random((2,3))         # you have to have double parentheses (())
X*=3
X

array([[3, 3, 3],
       [3, 3, 3]])

In [28]:
Y

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [25]:
Y+=X
Y

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

-----------------------------------------------------------------------------------------------------------------------------

In [29]:
# sum, min, max of an array

Y.sum()

3.290252281866131

In [30]:
Y.min()

0.14415961271963373

In [32]:
Y.max()

0.9504636963259353

In [33]:
# sum of each column, 

# min of each row, 

# cumulative sum along each row

Z=np.arange(12).reshape(3,4)
Z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
# sum of each column

Z.sum(axis=0)

array([12, 15, 18, 21])

In [35]:
# sum of each row

Z.min(axis=1)

array([0, 4, 8])

In [36]:
# cumulative sum along each row

Z.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

-------------------------------------------------------------------------------------------------------------------

One dimensional arrays can be sliced, indexed, and iterated over

In [40]:
T=np.arange(10)**3
T

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [41]:
T[2]

8

In [42]:
T[2:5]

array([ 8, 27, 64], dtype=int32)

In [43]:
T[:6:2]

array([ 0,  8, 64], dtype=int32)

In [45]:
# exchange every 2nd element with 1000 (???)

T[:6:2]=1000
T

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [46]:
# reversing the array

T[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [47]:
for i in T:
    print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998
