In [ ]:
Shape manipulation                                

If X is an array

X.shape  --  returns a tuple that indicates the number of dimensions in the array

X.ravel ( )  -- returns a flattened array

X.reshape ( , )  --  returns an array with a modified shape. It gives a new shape to an array without changing its data

X.T  -- returns an array, transposed

X.T.shape

X.shape

X.resize ( , )

-----------------------------------------------------------------------

Stacking

np.stack()

np.vstack()

np.hstack()

np.column_stack()

np.row_stack()  --  equavalent to vstack for any input arrays

In [2]:
import numpy as np
rg=np.random.default_rng(1)

X=np.floor(10*rg.random((3,4)))
X

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [3]:
X.shape

(3, 4)

In [4]:
X.ravel()  #returns the array X, flattened

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [5]:
X.reshape(6,2)  # returns an array with a modified shape  

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [6]:
X.T  # returns an array, transposed

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [7]:
X.T.shape

(4, 3)

In [8]:
X.shape

(3, 4)

In [9]:
X

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [31]:
X.resize((6,2))
X

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [12]:
X.reshape(3,-1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

--------------------------------------------------------------------------------------------------------------

You can stack arrays together along different axes 

In [13]:
Y = np.floor(10*rg.random((2,2)))
Y

array([[3., 7.],
       [3., 4.]])

In [14]:
Z=np.floor(10*rg.random((2,2)))
Z

array([[1., 4.],
       [2., 2.]])

In [30]:
np.stack((Y,Z))

array([[[3., 7.],
        [3., 4.]],

       [[1., 4.],
        [2., 2.]]])

In [15]:
np.vstack((Y,Z))

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.]])

In [16]:
np.hstack((Y,Z))

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [17]:
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays

from numpy import newaxis
np.column_stack((Y,Z))   # returns a 2D array

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [18]:
C=np.array([4,2])
D=np.array([3,8])

np.column_stack((C,D))   # returns a 2D array

array([[4, 3],
       [2, 8]])

In [20]:
np.hstack((C,D))

array([4, 2, 3, 8])

In [21]:
C[:, newaxis]  # views array C as 2D column vector

array([[4],
       [2]])

In [23]:
np.column_stack((C[:, newaxis], D[:, newaxis]))


array([[4, 3],
       [2, 8]])

In [25]:
np.hstack((C[:, newaxis], D[:, newaxis]))

array([[4, 3],
       [2, 8]])

In [27]:
np.column_stack is np.hstack

False

In [28]:
np.column_stack is np.vstack

False

In [29]:
np.row_stack is np.vstack

True