In [2]:
# selection sort repeatedly finds the minimum value from a list and makes swaps until the list is sorted

import numpy as np

def selection_sort(x):
    for i in range(len(x)):
        swap=i+np.argmin(x[i:])
        (x[i], x[swap])=(x[swap], x[i])
    return x

x=np.array([2,1,4,3,5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [4]:
# bogosort algorithm relies on pure chance to sort an array, it repeatedly applies a random shuffling of the array

def bogosort(y):
    while np.any(y[:-1] > y[1:]):
        np.random.shuffle(y)
        
    return y

y=np.array([2,1,4,3,5])
bogosort(y)


array([1, 2, 3, 4, 5])

In [5]:
# np.sort is more efficient than Python's built in sort function to sort lists

z=np.array([2,1,4,3,5])
np.sort(x)   # this is being used
x.sort()

print(x)

[1 2 3 4 5]


In [8]:
g=np.array([2,1,4,3,5])
h=np.argsort(x)

print(h)
x[h]

[0 1 2 3 4]


array([1, 2, 3, 4, 5])

In [10]:
# NumPy sorting algorithm: the ability to sort along specific rows or columns of multidimensional array using the axis argument

rand=np.random.RandomState(42)
x=rand.randint(0,10, (4,6))
print(x)

np.sort(x, axis=0) # sort each column of x

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [11]:
np.sort(x, axis=1)  # sort each row of x

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [13]:
# np.partition is not to sort entire array (??)

w=np.array([7,2,3,1,4,5,6,9,10])
np.partition(w,3)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])