In [2]:
import numpy as np
x=np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
x.ndim

2

In [4]:
x.shape

(3, 5)

In [5]:
x.size

15

In [6]:
x.dtype

dtype('int32')

In [7]:
x.itemsize

4

In [8]:
type(x)

numpy.ndarray

In [9]:
y=np.array([6,7,8])
y

array([6, 7, 8])

In [10]:
type(y)

numpy.ndarray

In [11]:
y.dtype

dtype('int32')

In [12]:
z=np.array([2.0, 3.5, 2.4])
z.dtype

dtype('float64')

In [13]:
A = np.array([(1.5, 2, 3), (4, 5, 6)])
A

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
A.dtype

dtype('float64')

In [15]:
A.ndim

2

In [18]:
#np.arange() function returns an array, a sequence of numbers

x=np.arange(3,10,2)
x

array([3, 5, 7, 9])

In [19]:
# returns 20 elements, from 2 to 10

z=np.linspace(2,10,20)
z

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])