Array slicing

In [1]:
import numpy as np
np.random.seed(0) # seed for reproductibility

x1=np.random.randint (10, size=6)
x2=np.random.randint (10, size=(3,4))
x3=np.random.randint (10, size=(3,4,5))

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x1[0]

5

In [5]:
x1[4]

7

In [6]:
x1[-1]

9

In [7]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
x2[0,0]

3

In [9]:
x2[2,0]

1

In [10]:
x2[2,-1]

7

In [11]:
x2[1,-1]

8

In [12]:
x2[3,0]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [14]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[:5]

array([0, 1, 2, 3, 4])

In [16]:
# slicing starting from index number 5

x[5:]

array([5, 6, 7, 8, 9])

In [17]:
#middle sub-array

x[4:7]

array([4, 5, 6])

In [18]:
# every other element

x[::2]

array([0, 2, 4, 6, 8])

In [19]:
# every other element, starting at index number 1

x[1::2]

array([1, 3, 5, 7, 9])

In [20]:
# all elements, reversed
# a negative step value is a convenient way to reverse an array

x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
# reversed every other, from index number 5

x[5::-2]

array([5, 3, 1])

In [22]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
# two rows, three columns

x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [24]:
x2[:3, :2]

array([[3, 5],
       [7, 6],
       [1, 6]])

In [25]:
# all rows (in this case 3), every other column

x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [26]:
# in full reverse...

x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [29]:
# first column of x2

print(x2 [:,0])

[3 7 1]


In [30]:
# fist row of x2

print(x2 [0,:])

[3 5 2 4]


In [31]:
# equivalent to the above code
# first row of x2

print(x2 [0])

[3 5 2 4]
